### ISSUE TITLE
导航栏当前页切换问题

### ISSUE THREAD

**Issue by wuyanxin** [ggice/icer#1]
你这个主题设计得挺简洁，很好看，想通过你的基础上创建自己的主题

我在看你的源码的时候发现了一个问题
我看这里切换导航栏是使用js为当前链接添加class=“select”
其实只要你在导航栏添加的时候使用“/”结尾的话
navigation.hbs中的`{{#if current}} nav-current{{/if}}`就会生效了

所以我猜你为FRONT-END设置的链接是`https://ice.gs/tag/front-end-development`
设置成`https://ice.gs/tag/front-end-development/`nav-current这个class就会生效了

不过现在新版的ghost有没有加“/”都支持了，看[这里](https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/navigation.js)

这是我的拙见

最后，谢谢你的主题

**Comment by GGICE** [comment]
谢谢你的反馈，我会近期尽快修改。

**Comment by GGICE** [comment]
已经修改！
