### ISSUE TITLE
无法显示导航栏

### ISSUE THREAD

**Issue by clayton-k** [ggice/icer#6]
安装了你的主题后，发现无法像你的网站一样显示右上角的导航栏，这个bug要怎么修复？很喜欢你的主题，很简洁美观。

**Comment by GGICE** [comment]
谢谢，是有这个问题，你后台上传下Blog Logo，导航条就会显示了，后期会修复这个问题。

**Comment by clayton-k** [comment]
啊，原来是这样，谢谢呐😁
